### ISSUE TITLE
When running clearblade-hot-reload, it can't find module 'chalk'

### ISSUE THREAD

**Issue by bike-bill** [ClearBlade/clearblade-hot-reload#4]
I installed clearblade-hot-reload as prescribed: 
npm i -g @clearblade/clearblade-hot-reload
and run it in a newly exported clearblade platform project like this:
clearblade-hot-reload start

The command does not run but errors out with this:

$ clearblade-hot-reload start
internal/modules/cjs/loader.js:628
    throw err;
    ^

Error: Cannot find module 'chalk'
Require stack:
- /home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/utils/error.js
- /home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/index.js
- /home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/bin/clearblade-hot-reload
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)
    at Function.Module._load (internal/modules/cjs/loader.js:527:27)
    at Module.require (internal/modules/cjs/loader.js:683:19)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (/home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/utils/error.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:777:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)
    at Module.load (internal/modules/cjs/loader.js:643:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Module.require (internal/modules/cjs/loader.js:683:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/utils/error.js',
    '/home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/index.js',
    '/home/william/.nvm/versions/node/v12.7.0/lib/node_modules/@clearblade/clearblade-hot-reload/bin/clearblade-hot-reload'
  ]
}

The same error is also produced if I run:
clearblade-hot-reload
in an empty directory.

**Comment by sh3nan1gans** [comment]
@bike-bill - Have you tried using cb-dev-kit https://github.com/ClearBlade/cb-dev-kit/ ? cb-dev-kit uses this repo internally and is working with hot reload. Going to close this issue in favor of using cb-dev-kit

**Comment by sh3nan1gans** [comment]
To fix this, we just need to move chalk to be a dependency instead of a devDependency
